-- Table: public.deck
CREATE TABLE IF NOT EXISTS public.deck
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    topic character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT deck_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.deck
    OWNER to backend;

-- Table: public.card
CREATE TABLE IF NOT EXISTS public.card
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    question character varying COLLATE pg_catalog."default" NOT NULL,
    answer character varying COLLATE pg_catalog."default" NOT NULL,
    deck_id bigint NOT NULL,
    CONSTRAINT card_pkey PRIMARY KEY (id),
    CONSTRAINT deckidconstraint FOREIGN KEY (deck_id)
        REFERENCES public.deck (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

ALTER TABLE IF EXISTS public.card
    OWNER to backend;