openapi: 3.0.3
info:
  title: Flash Card Learning Platform API
  description: API for evaluating and storing flash card learning sessions
  version: 1.0.0
  contact:
    name: Flash Card Learning Platform
servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://api.flashcard-platform.com
    description: Production server

paths:
  /evaluate:
    post:
      summary: Evaluate user's answer against the correct answer
      description: Evaluates the user's answer and returns either a success message or a hint for improvement
      operationId: evaluate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/History'
            examples:
              success_case:
                summary: Success case example
                description: Example where user eventually gets the correct answer
                value:
                  messages:
                    - role: assistant
                      type: question
                      message: What is the capital of France?
                    - role: user
                      type: answer
                      message: Kiel
                    - role: assistant
                      type: hint
                      message: Think of the city known as the 'City of Light' and famous for the Eiffel Tower.
                    - role: user
                      type: answer
                      message: Paris
                    - role: assistant
                      type: success
                      message: Correct!
      responses:
        '200':
          description: Evaluation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
              examples:
                success:
                  summary: Success response
                  value:
                    type: success
                    message: Correct!
                hint:
                  summary: Hint response
                  value:
                    type: hint
                    message: Think of the city known as the 'City of Light' and famous for the Eiffel Tower.
        '400':
          description: Bad request - invalid history format
        '500':
          description: Internal server error

  /store:
    post:
      summary: Store the complete learning session history
      description: Stores the entire conversation history for the learning session
      operationId: store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/History'
            examples:
              completed_session:
                summary: Completed learning session
                description: Example of a completed learning session
                value:
                  messages:
                    - role: assistant
                      type: question
                      message: What is the capital of France?
                    - role: user
                      type: answer
                      message: Kiel
                    - role: assistant
                      type: hint
                      message: Think of the city known as the 'City of Light' and famous for the Eiffel Tower.
                    - role: user
                      type: answer
                      message: Paris
                    - role: assistant
                      type: success
                      message: Correct!
      responses:
        '200':
          description: History stored successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "History stored successfully"
                  sessionId:
                    type: string
                    format: uuid
                    example: "123e4567-e89b-12d3-a456-426614174000"
        '400':
          description: Bad request - invalid history format
        '500':
          description: Internal server error

components:
  schemas:
    History:
      type: object
      required:
        - messages
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
          description: Array of conversation messages

    Message:
      type: object
      required:
        - role
        - type
        - message
      properties:
        role:
          type: string
          enum: [assistant, user]
          description: Role identifier for the message sender
        type:
          type: string
          enum: [question, answer, hint, success]
          description: Type of message content
        message:
          type: string
          description: The message content
